[package]
name = "fast"
version = "0.1.0"
authors = ["PhysicalLinkage <physical-linkage@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.67"
socket = "0.0.7"

